/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jhraxjlvmixhzvzbjjsw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocmF4amx2bWl4aHp2emJqanN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTczODAsImV4cCI6MjA3Nzc3MzM4MH0.-TZoazOS2sHjIvhVh5A-24sE0cXtF8hggC9vPT0PF3Y"